name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: '55 13 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build katbury and run unit tests
        run: |
          cargo build --verbose --all --release
          cargo test
          cargo test --ignored || echo FAILURES ALLOWED
        
      - name: Upload macOS release build
        uses: actions/upload-artifact@v2
        if: contains(matrix.os, 'macos')
        with:
          name: katbury.macos
          path: target/release/katbury

      - name: Upload Linux release build
        uses: actions/upload-artifact@v2
        if: contains(matrix.os, 'ubuntu')
        with:
          name: katbury.linux
          path: target/release/katbury            


        
        
