name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: '55 13 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build katbury and run unit tests
        run: |
          cargo build --verbose --all --release
          cargo test
        
      - name: Upload macOS release build
        uses: actions/upload-artifact@v2
        if: contains(matrix.os, 'macos')
        with:
          name: ffs.macos
          path: target/release/ffs

      - name: Upload Linux release build
        uses: actions/upload-artifact@v2
        if: contains(matrix.os, 'ubuntu')
        with:
          name: ffs.linux
          path: target/release/ffs            


        
        
